### ISSUE TITLE
Is `scala-steward-org/scala-steward-action` an alternative?

### ISSUE THREAD

**Issue by akash1810** [guardian/scala-steward-public-repos#65]
Usage of this repository requires admin access:

> Grant [our GitHub app](https://github.com/apps/gu-scala-steward-public-repos) access to your repo (click [Configure](https://github.com/apps/gu-scala-steward-public-repos/installations/26822732) - you may need a repo admin to do this)

Might https://github.com/scala-steward-org/scala-steward-action provide an alternative? It looks like we'll need GitHub App properties stored as repository secrets. We should be able to utilise https://github.com/guardian/github-secret-access to ease obtaining these.

Pros to using the action:
- Two fewer repositories to maintain (this, and [private repo](https://github.com/guardian/scala-steward-private-repos))
- The cadence which Scala Steward runs can be customised per repository

**Comment by rtyley** [comment]
Just to clarify, we already use `scala-steward-org/scala-steward-action`:

https://github.com/guardian/scala-steward-public-repos/blob/57498230614af4b1329ac1ac51bfb3f9b24eea2b/.github/workflows/reusable-scala-steward.yml#L36

...but I think you're suggesting that instead of having a single shared workflow (or at least, one public & one private), every repo that wants Scala Steward has its own copy of a file like [public-repos-scala-steward.yml](https://github.com/guardian/scala-steward-public-repos/blob/main/.github/workflows/public-repos-scala-steward.yml)?

Just to follow up on your opening point (_"Usage of this repository requires admin access:"_ - in response to _"(click [Configure](https://github.com/apps/gu-scala-steward-public-repos/installations/26822732) - you may need a repo admin to do this)"_) - to clarify, this is admin access on **the repository that you want to add Scala Steward to** - so if you want to add Scala Steward to [guardian/redirect-resolver](https://github.com/guardian/redirect-resolver), you need _admin access_ on guardian/redirect-resolver - but that seems reasonable?


Overall, I'd prefer to remove boilerplate, so adding copies of [public-repos-scala-steward.yml](https://github.com/guardian/scala-steward-public-repos/blob/main/.github/workflows/public-repos-scala-steward.yml) to every Scala repo is not attractive to me! Regarding the pros you listed:

* _Two fewer repositories to maintain (this, and [private repo](https://github.com/guardian/scala-steward-private-repos))_ - I don't think the maintenance burden of these umbrella repos in themselves is that high? There are definitely problems with Scala Steward runs, but they are generally due to problems with people's repos, and it gives better visibility to have that in one place.
* _The cadence which Scala Steward runs can be customised per repository_ - the cadence at which Scala Steward creates PRs can **already** customised per repository - you can add an additional [`.scala-steward.conf`](https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md) in the top level of the repo, and it will override the common [scala-steward.conf](https://github.com/guardian/scala-steward-public-repos/blob/main/scala-steward.conf) file. If this is failing, it's generally due to https://github.com/guardian/scala-steward-public-repos/issues/60

I might have banged on a bit here, apologies if so - would be very happy to have a chat to help me understand more, if you'd like!

**Comment by akash1810** [comment]
Thanks for taking the time to look/explain @rtyley.

> Just to clarify, we already use `scala-steward-org/scala-steward-action`

I hadn't realised we're already using the action; I thought we had some infra of our own. I should have checked this first, apologies.

> you need _admin access_ on guardian/redirect-resolver - but that seems reasonable?

Agreed, to this, and your other comments too!

Closing.
